test comment workflow

diff --git a/.github/workflows/beam_PostCommit_Go.yml b/.github/workflows/beam_PostCommit_Go.yml
--- a/.github/workflows/beam_PostCommit_Go.yml
+++ b/.github/workflows/beam_PostCommit_Go.yml
@@ -76,29 +76,14 @@ jobs:
           comment_phrase: ${{ matrix.job_phrase }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
           github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
-      - name: Setup environment
-        uses: ./.github/actions/setup-environment-action
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Authenticate on GCP
-        uses: google-github-actions/setup-gcloud@v0
-        with:
-          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
-          service_account_key: ${{ secrets.GCP_SA_KEY }}
-          project_id: ${{ secrets.GCP_PROJECT_ID }}
-          export_default_credentials: true
-      - name: GCloud Docker credential helper
+      - name: Simple api
         run: |
-          gcloud auth configure-docker us.gcr.io
-      - name: run Go PostCommit script
-        uses: ./.github/actions/gradle-command-self-hosted-action
-        env:
-          USER: github-actions
-        with:
-          gradle-command: :goPostCommit
-          arguments: |
-            --no-parallel \
-            -Pdocker-repository-root=us.gcr.io/apache-beam-testing/github-actions
+          TEST=$(curl https://simpleapi.volatilemolotov.com/test4 | jq -r '.fail')
+          echo $TEST
+          if [ "$TEST" == "true" ]; then
+            echo "Simple api failed"
+            exit 1
+          fi
   post_dispatch_update:
     if: github.event_name == 'workflow_dispatch'
     uses: ./.github/workflows/comment-trigger.yml
