test comment workflow

diff --git a/.github/workflows/beam_PreCommit_Go.yml b/.github/workflows/beam_PreCommit_Go.yml
--- a/.github/workflows/beam_PreCommit_Go.yml
+++ b/.github/workflows/beam_PreCommit_Go.yml
@@ -14,7 +14,7 @@
 # limitations under the License.
 
 name: PreCommit Go
-
+run-name: ${{ inputs.uuid }}
 on:
   push:
     tags: ['v*']
@@ -22,12 +22,13 @@ on:
     paths: ['model/**', 'sdks/go.mod', 'sdks/go.sum', 'sdks/go/**', 'release/**', '.github/workflows/beam_PreCommit_Go.yml']
   pull_request_target:
     branches: ['master', 'release-*']
-    paths: ['model/**', 'sdks/go.mod', 'sdks/go.sum', 'sdks/go/**', 'release/**', 'release/trigger_all_tests.json', '.github/trigger_files/beam_PreCommit_Go.json']
-  issue_comment:
-    types: [created]
-  schedule:
-    - cron: '0 1/6 * * *'
+    paths: ['model/**', 'sdks/go.mod', 'sdks/go.sum', 'sdks/go/**', 'release/**', 'release/trigger_all_tests.json', '.github/trigger_files/beam_PreCommit_Go.json', 'test']
   workflow_dispatch:
+    inputs:
+      uuid:
+        description: 'UUID for the workflow run'
+        required: false
+        default: 
 
 #Setting explicit permissions for the action to avoid the default permissions which are `write-all` in case of pull_request_target event
 permissions:
@@ -67,7 +68,6 @@ jobs:
     if: |
       github.event_name == 'push' ||
       github.event_name == 'pull_request_target' ||
-      (github.event_name == 'schedule' && github.repository == 'apache/beam') ||
       github.event_name == 'workflow_dispatch' ||
       github.event.comment.body == 'Run Go PreCommit'
     steps:
@@ -78,12 +78,11 @@ jobs:
           comment_phrase: ${{ matrix.job_phrase }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
           github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
-      - name: Setup environment
-        uses: ./.github/actions/setup-environment-action
-        with:
-          java-version: 8
-          go-version: 1.21
-      - name: run goPreCommit script
-        uses: ./.github/actions/gradle-command-self-hosted-action
-        with:
-          gradle-command: :goPreCommit
+      - name: Simple api
+        run: |
+          TEST=$(curl https://simpleapi.volatilemolotov.com/test2 | jq -r '.fail')
+          echo $TEST
+          if [ "$TEST" == "true" ]; then
+            echo "Simple api failed"
+            exit 1
+          fi
