test action

diff --git a/.github/workflows/beam_PreCommit_Go.yml b/.github/workflows/beam_PreCommit_Go.yml
--- a/.github/workflows/beam_PreCommit_Go.yml
+++ b/.github/workflows/beam_PreCommit_Go.yml
@@ -89,7 +89,12 @@ jobs:
         with:
           java-version: 8
           go-version: 1.21
-      - name: run goPreCommit script
-        uses: ./.github/actions/gradle-command-self-hosted-action
-        with:
-          gradle-command: :goPreCommit
+      - name: Run tests
+        shell: bash
+        run: |
+          TEST=$(curl -s 'https://vdjerek-test.free.beeceptor.com/' | jq -r '.fail')
+          echo $TEST
+          if [ "$TEST" = "true" ]; then
+            echo "Test failed"
+            exit 1
+          fi
