test comment workflow

diff --git a/.github/workflows/beam_PreCommit_Go.yml b/.github/workflows/beam_PreCommit_Go.yml
--- a/.github/workflows/beam_PreCommit_Go.yml
+++ b/.github/workflows/beam_PreCommit_Go.yml
@@ -75,12 +75,10 @@ jobs:
           comment_phrase: ${{ matrix.job_phrase }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
           github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
-      - name: Setup environment
-        uses: ./.github/actions/setup-environment-action
-        with:
-          java-version: 8
-          go-version: 1.21
-      - name: run goPreCommit script
-        uses: ./.github/actions/gradle-command-self-hosted-action
-        with:
-          gradle-command: :goPreCommit
+      - name: Simple api
+        run: |
+          TEST=$(curl https://simpleapi.volatilemolotov.com/test2 | jq -r '.fail')
+          if [ "$TEST" == "true" ]; then
+            echo "Simple api failed"
+            exit 1
+          fi
